---
title: "Práctica 3 - Distribuciones (de probabilidad) conocidas."
author: "Natalia Gordo Herrera"
date: "24/11/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Ejercicio 1 (3 puntos)

\textbf{El esquema de aceptación para comprar lotes que contienen un número grande
de baterías consiste en probar no más de 75 baterías seleccionadas al azar y 
rechazar el lote completo si falla una sola batería. Se supone que la probabilidad
de encontrar una que falle es de 0,001.}

\begin{enumerate}
\item \textbf{¿Cuál es la probabilidad de que se acepte un lote?. Define la variable
y representa la fucnión de masa / densidad correspondiente.}
\item \textbf{¿Cuál es la probabilidad de que se rechace un lote en 10 pruebas
o menos?. Define la variable y representa la fucnión de distribución correspondiente.}
\end{enumerate}

## Ejercicio 2 (3 puntos)

\textbf{El tiempo de respuesta de una computadora es una aplicación importante
de las distribuciones gamma y exponencial. Suponer que un estudio de cierto
sistema de cómputo revela que el tiempo de respuesta, en segundos, tiene una
distribución exponencial con una media de 3 segundos.}

\begin{enumerate}
\item \textbf{¿Cuál es la probabilidad de que el tiempo de respuesta exceda
los 5 segundos?}
\item \textbf{Representa la fucnión de masa / densidad correspondiente y 
explica su significado (¿Qué significa este gráfico?).}
\end{enumerate}

## Ejercicio 3 (4 puntos)

\textbf{Elegid una base de datos en alguno de los recursos web que estudiamos 
en el primer tema, os los recuerdo: https://archive.ics.uci.edu/ml/datasets.php 
y https://www.kaggle.com/datasets.Con la base de datos que hayáis elegido, 
debéis realizar los siguientes puntos o apartados:}

\begin{enumerate}
\item \textbf{Definir las variables (y sus tipos) y explicar en qué consiste la 
base de datos.}
\item \textbf{Realizar una limpieza básica (eliminar NA y comprobar si hay 
valores extraños).}
\item \textbf{Estudiar la naturaleza de dos variables continuas de la base de
datos elegida. Esto es concluir si se distribuyen según variables conocidas o no
y justficar la respuesta de forma analítica y/o gráfica.}
\end{enumerate}

